# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' For each pixel, compute which cells drain _into_ that pixel.
#'
#' @inheritParams accumulate_flow
#' @return Matrix containing the summed direction values of all
#'         adjacent pixels that flow into this pixel. Value is
#'         zero if no adjacent pixels flow into this pixel (i.e,
#'         the pixel is a sink.)
#' @export
create_inward_dir_matrix <- function(directions, wrapX, wrapY) {
    .Call(`_wsim_lsm_create_inward_dir_matrix`, directions, wrapX, wrapY)
}

aggregate_flows <- function(flows, directions, factor, wrapX, wrapY) {
    .Call(`_wsim_lsm_aggregate_flows`, flows, directions, factor, wrapX, wrapY)
}

disaggregate_amount <- function(mat, factor) {
    .Call(`_wsim_lsm_disaggregate_amount`, mat, factor)
}

#' Accumulate flow, given flow directions and weights.
#'
#' @param directions a matrix of flow directions, where directions are represented
#' by the following values:
#'
#' * east: 1
#' * southeast: 2
#' * south: 4
#' * southwest: 8
#' * west: 16
#' * northwest: 32
#' * north: 64
#' * northeast: 128
#' * none (sink cell): NA
#'
#' @param weights a matrix of weights, representing the amount of flow originating at
#' each cell
#'
#' @param wrapX should flow exiting the X-limits of the model be routed to the other side?
#' @param wrapY should flow exiting the Y-limits of the model be routed to the other side?
#'
#' @return a matrix of accumulated flow values
#' @md
#' @export
accumulate_flow <- function(directions, weights, wrapX, wrapY) {
    .Call(`_wsim_lsm_accumulate_flow`, directions, weights, wrapX, wrapY)
}

#' Perform a basin-to-basin flow accumulation
#'
#' @param basin_ids       a vector of basin ids
#' @param downstream_ids  a vector of downstream basin ids,
#'                        aligned with the entries in \code{basin_ids}
#' @param flows           a vector of flows generated in each basin,
#'                        aligned with the entries in \code{basin_ids}
#' @return a vector of outlet flows for each basin (including flow generated
#'         within the basin), aligned with the entries in \code{basin_ids}
#' @export
accumulate <- function(basin_ids, downstream_ids, flows) {
    .Call(`_wsim_lsm_accumulate`, basin_ids, downstream_ids, flows)
}

#' Compute the sum of flow originating in downstream basins
#'
#' @param basin_ids       a vector of basin ids
#' @param downstream_ids  a vector of downstream basin ids,
#'                        aligned with the entries in \code{basin_ids}
#' @param flows           a vector of flows generated in each basin,
#'                        aligned with the entries in \code{basin_ids}
#' @return a vector of downstream flows for each basin (excluding flow generated
#'         within the basin), aligned with the entries in \code{basin_ids}
#' @export
downstream_flow <- function(basin_ids, downstream_ids, flows) {
    .Call(`_wsim_lsm_downstream_flow`, basin_ids, downstream_ids, flows)
}

#' Replace NA values with a specified constant
#'
#' @param v                 a numeric vector that may
#'                          contain NA values
#' @param replacement_value a constant with with NA values
#'                          should be replaced
#'
#' @return a copy of \code{v} with NA values replaced by
#'         \code{replacement_value}
#' @export
coalesce <- function(v, replacement_value) {
    .Call(`_wsim_lsm_coalesce`, v, replacement_value)
}

#' Determine if a given year is a leap year
#'
#' @param y integer representation of year
#' @return TRUE if the given year is a leap year
is_leap_year <- function(y) {
    .Call(`_wsim_lsm_is_leap_year`, y)
}

day_hours <- function(sun_lat, earth_lat) {
    .Call(`_wsim_lsm_day_hours`, sun_lat, earth_lat)
}

#' Return the day length at given latitude(s)
#'
#' @param latitudes a vector of latitudes
#' @param year numeric year
#' @param month numeric month
#' @param day numeric day of month
#' @return day length in hours
#'
#' @export
day_length <- function(latitudes, year, month, day) {
    .Call(`_wsim_lsm_day_length`, latitudes, year, month, day)
}

#' Return the monthly average day length at given latitude(s)
#'
#' @param latitudes a vector of latitudes
#' @param year numeric year
#' @param month numeric month
#' @return day length in hours
#'
#' @export
average_day_length <- function(latitudes, year, month) {
    .Call(`_wsim_lsm_average_day_length`, latitudes, year, month)
}

#' Compute hydrological parameters over a multi-day timestep with precipitation on some days
#'
#' Precipitation is evenly divided over a set of evenly-spaced "wet days."
#' Snowmelt is evenly divided over the multi-day timestep.
#'
#' @param P  precipitation for the time step [L]
#' @param Sa snow accumulation for the time step [L]
#' @param Sm snow melt for the time step [L]
#' @param E0 potential evapotranspiration for the time step [L]
#' @param Ws soil moisture at start of time step [L]
#' @param Wc soil moisture holding capacity [L]
#' @param nDays number of days in time step [-]
#' @param pWetDays percentage of days with precipitation [-]
#' @return a List of hydrological parameters:
#'           dWdt:   change in soil moisture [L]
#'           Ws_ave: average soil moisture over timestep [L],
#'           E:      evapotranspiration [L]
#'           R:      runoff [L]
#'
#' @export
daily_hydro <- function(P, Sa, Sm, E0, Ws, Wc, nDays, pWetDays) {
    .Call(`_wsim_lsm_daily_hydro`, P, Sa, Sm, E0, Ws, Wc, nDays, pWetDays)
}

#' Compute hydrological parameters for all pixels
#'
#' @param P  precipitation for the time step [L]
#' @param Sa snow accumulation for the time step [L]
#' @param Sm snow melt for the time step [L]
#' @param E0 potential evapotranspiration for the time step [L]
#' @param Ws soil moisture at start of time step [L]
#' @param Wc soil moisture holding capacity [L]
#' @param nDays number of days in time step [-]
#' @param pWetDays percentage of days with precipitation [-]
#' @return a List of vectors of hydrological parameters:
#'           dWdt:   change in soil moisture [L]
#'           Ws_ave: average soil moisture over timestep [L],
#'           E:      evapotranspiration [L]
#'           R:      runoff [L]
#'
#' @export
daily_hydro_loop <- function(P, Sa, Sm, E0, Ws, Wc, nDays, pWetDays) {
    .Call(`_wsim_lsm_daily_hydro_loop`, P, Sa, Sm, E0, Ws, Wc, nDays, pWetDays)
}

#' Generate a list of days in which precipitation occurs
#'
#' @param nDays number of days in time period
#' @param pWetDays fraction of days in which precipitation falls
#' @return A list of days in which precipitation falls, starting at 1
#' @export
make_wet_day_list <- function(nDays, pWetDays) {
    .Call(`_wsim_lsm_make_wet_day_list`, nDays, pWetDays)
}

#' Compute precipitation for each day in a multi-day period
#'
#' @param P_total total precipitation for time period
#' @param nDays number of days in time period
#' @param pWetDays fraction of days in which precipitation occurs
#' @export
make_daily_precip <- function(P_total, nDays, pWetDays) {
    .Call(`_wsim_lsm_make_daily_precip`, P_total, nDays, pWetDays)
}

runoff_detained_snowpack_cpp <- function(Ds, Xs, melt_month, z) {
    .Call(`_wsim_lsm_runoff_detained_snowpack_cpp`, Ds, Xs, melt_month, z)
}

#' Calculate detained runoff and snowmelt
#'
#' @param R runoff
#' @param Pr precipitation
#' @param P  net precipitation Pr - Sa + Sm
#' @param Sm snowmelt
#' @param Dr detained runoff
#' @param Ds detained snowmelt
#' @param z  elevation
#' @param melt_month number of consecutive
#'        months of melting conditions
calc_detained <- function(R, Pr, P, Sm, Dr, Ds, z, melt_month) {
    .Call(`_wsim_lsm_calc_detained`, R, Pr, P, Sm, Dr, Ds, z, melt_month)
}

#' Snow accumulation
#'
#' Compute snow accumulation, assuming that all precipitation
#' is snowfall if the temperature less than -1 C, and that no
#' precipitation is snowfall if the temperature is unknown or
#' greater than or equal to -1 C.
#'
#' @param Pr Measured precipitation (mm/day)
#' @param T  Average daily temperature (C)
#' @return snow accumulation in mm
#' @export
snow_accum <- function(Pr, T) {
    .Call(`_wsim_lsm_snow_accum`, Pr, T)
}

#' Calculate snowmelt
#'
#' Melting occurs when the temperature is greater than -1 C.
#' If elevation is less than 500 m, all snow will melt in one timestep.
#' If elevation is greater than 500m, snowmelt will be divided over
#' two timesteps.
#'
#' @param snowpack Snowpack (mm)
#' @param melt_month Number of consecutive months in which melting conditions
#'                   have been present
#' @param T Average temp (C)
#' @param z Elevation (m)
#' @return Snowmelt (mm/month)
#' @export
snow_melt <- function(snowpack, melt_month, T, z) {
    .Call(`_wsim_lsm_snow_melt`, snowpack, melt_month, T, z)
}

#' Unitless drying function
#' @param Ws Soil moisture (mm)
#' @param Wc Soil water holding capacity (mm)
#' @param E0 Potential evapotranspiration (mm/day)
#' @param P  Effective precipitation (mm/day)
#' @return   Magnitude of decline in soil moisture (mm/day)
#' @export
g <- function(Ws, Wc, E0, P) {
    .Call(`_wsim_lsm_g`, Ws, Wc, E0, P)
}

#' Change in soil moisture
#' @param P   Effective precipitation (mm/day)
#' @param E0  Potential evapotranspiration (mm/day)
#' @param Ws  Soil moisture (mm)
#' @param Wc  Soil moisture holding capacity (mm)
#'
#' @return    Change in soil moisture (mm/day)
#' @export
soil_moisture_change <- function(P, E0, Ws, Wc) {
    .Call(`_wsim_lsm_soil_moisture_change`, P, E0, Ws, Wc)
}

