#' Run the model using matrices
#'
#' @param static a list containing static inputs to the model
#' @param state a list containing an input state for the model
#' @param forcing a list containing forcing data for the model
#' @return a list containing model outputs and a state for the next time step.
#' @useDynLib wsim.lsm, .registration=TRUE
#' @export
run <- function(static, state, forcing) {
  melt_month <- ifelse(
    forcing$T > -1,
    state$snowmelt_month + 1,
    0
  )

  # guard against NODATA values in state variables
  # this is necessary when reading IniData generated by older
  # versions of the LSM, which did not scrub NODATA values from outputs
  state$Snowpack[is.na(state$Snowpack)] <- 0.0
  state$Dr[is.na(state$Dr)] <- 0.0
  state$Ds[is.na(state$Ds)] <- 0.0
  state$Ws[is.na(state$Ws)] <- 0.0

  # estimate snow accumulation and snowmelt
  Sa <- snow_accum(forcing$Pr, forcing$T)
  Sm <- ifelse(is.na(Sa), NA, snow_melt(state$Snowpack, melt_month, forcing$T, static$elevation))

  P <- P_effective(forcing$Pr, Sa, Sm)

  E0 <- e_potential(forcing$daylength, forcing$T, forcing$nDays)

  hydro <- daily_hydro_loop(P, Sm, E0, state$Ws, static$Wc, forcing$nDays, forcing$pWetDays)
  dWdt <- matrix(hydro$dWdt, nrow=nrow(forcing$T), ncol=ncol(forcing$T))
  E <- matrix(hydro$E, nrow=nrow(forcing$T), ncol=ncol(forcing$T))
  R <- matrix(hydro$R, nrow=nrow(forcing$T), ncol=ncol(forcing$T))
  Ws_ave <- matrix(hydro$Ws_ave, nrow=nrow(forcing$T), ncol=ncol(forcing$T))

  Xr <- calc_Xr(R, forcing$Pr, P)
  Xs <- calc_Xs(Sm, R, P)

  Rp <- calc_Rp(state$Dr, Xr)
  Rs <- runoff_detained_snowpack(state$Ds, Xs, melt_month, static$elevation)

  revised_runoff <- Rp + Rs

  # Calculate changes in detention state variables
  dDsdt = Xs - Rs

  next_state <- list(
    Snowpack= state$Snowpack + ifelse(is.na(Sa - Sm), 0.0, Sa - Sm),
    snowmelt_month= melt_month,
    Ws= state$Ws + ifelse(is.na(dWdt), 0.0, dWdt),
    Dr= Rp, # TODO resolve discrepancy with manual
    Ds= state$Ds + ifelse(is.na(dDsdt), 0.0, dDsdt)
  )

  obs <- list(
    dayLength= forcing$daylength,
    dWdt= dWdt,
    E= E,
    EmPET= E - E0,
    P_net= P,
    PET= E0,
    PETmE= E0 - E,
    Pr= forcing$Pr,
    RO_mm= revised_runoff,
    RO_m3= revised_runoff*static$area_m2/1000,
    Runoff_mm= R,
    Runoff_m3= R*static$area_m2/1000,
    Sa= Sa,
    Sm= Sm,
    T= forcing$T,
    Ws= Ws_ave
  )
  obs$Bt_RO <- accumulate_flow(obs$RO_m3,  static$flow_directions)
  obs$Bt_Runoff <- accumulate_flow(obs$Runoff_m3, static$flow_directions)

  return(list(
    obs=obs,
    next_state=next_state
  ))
}
