# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Aggregate a matrix, reducing a block of cells by the arithmetic mean of the defined values
#' 
#' @inheritParams aggregate_mean_doy
#' @export
aggregate_sum <- function(mat, factor) {
    .Call(`_wsim_agriculture_aggregate_sum`, mat, factor)
}

#' Aggregate a matrix, reducing a block of cells by the arithmetic mean of the defined values
#' 
#' @inheritParams aggregate_mean_doy
#' @export
aggregate_mean <- function(mat, factor) {
    .Call(`_wsim_agriculture_aggregate_mean`, mat, factor)
}

#' Aggregate a matrix, reducing a block of cells to a single cell by averaging the day of the year
#' 
#' @param mat    a matrix
#' @param factor factor by which to reduce the matrix; every \code{factor} rows will
#'               be reduced to a single row, and every \code{factor} columns will be
#'               reduced to a single column.
#' @export
aggregate_mean_doy <- function(mat, factor) {
    .Call(`_wsim_agriculture_aggregate_mean_doy`, mat, factor)
}

#' Determine if a given day is within the growing season
#' 
#' @param day_of_year  numerical day of year, 1-365
#' @param plant_date   day of year when planting occurs
#' @param harvest_date day of year when harvest occurs
#' @return            TRUE if day is within growing season, FALSE otherwise
#' @export
is_growing_season <- function(day_of_year, plant_date, harvest_date) {
    .Call(`_wsim_agriculture_is_growing_season`, day_of_year, plant_date, harvest_date)
}

#' Determine the number of days since planting
#' 
#' @inheritParams is_growing_season
#' @return number of days since planting or \code{NA_integer_} if 
#'         \code{day_of_year} is outside the growing season.
#' @export
days_since_planting <- function(day_of_year, plant_date, harvest_date) {
    .Call(`_wsim_agriculture_days_since_planting`, day_of_year, plant_date, harvest_date)
}

#' Determine the number of days until harvest
#' 
#' @inheritParams is_growing_season
#' @return number of days until harvest or \code{NA_integer_} if 
#'         \code{day_of_year} is outside the growing season.
#' @export
days_until_harvest <- function(day_of_year, plant_date, harvest_date) {
    .Call(`_wsim_agriculture_days_until_harvest`, day_of_year, plant_date, harvest_date)
}

#' Determine the first growing day in a range
#' 
#' @param from first day in range
#' @param to   last day in range
#' @inheritParams is_growing_season
#' @return first day between \code{from} and \code{to} that is
#'         within the growing season, or \code{NA_integer_} if no
#'         day is within the growing season.
#' @export
first_growing_day <- function(from, to, plant_date, harvest_date) {
    .Call(`_wsim_agriculture_first_growing_day`, from, to, plant_date, harvest_date)
}

#' Determine the last growing day in a range
#' 
#' @inheritParams first_growing_day
#' @return last day between \code{from} and \code{to} that is
#'         within the growing season, or \code{NA_integer_} if no
#'         day is within the growing season.
#' @export
last_growing_day <- function(from, to, plant_date, harvest_date) {
    .Call(`_wsim_agriculture_last_growing_day`, from, to, plant_date, harvest_date)
}

#' Count growing days within a day interval
#' 
#' Provide the number of growing days in the latest growing season represented
#' by the interval spanning from \code{from} to \code{to}. If \code{from} and
#' \code{to} are not in the same growing season, only the days in the same
#' growing season as \code{to} will be returned.
#' 
#' @inheritParams first_growing_day
#' 
#' @export
growing_days_this_season <- function(from, to, plant_date, harvest_date) {
    .Call(`_wsim_agriculture_growing_days_this_season`, from, to, plant_date, harvest_date)
}

#' Return the number of growing days within an interval that contribute to a harvest in the current year.
#' 
#' @inheritParams first_growing_day
#' 
#' @export
growing_days_this_year <- function(from, to, plant_date, harvest_date) {
    .Call(`_wsim_agriculture_growing_days_this_year`, from, to, plant_date, harvest_date)
}

#' Return the number of growing days within an interval that contribute to a harvest in the following year.
#' 
#' @inheritParams first_growing_day
#' 
#' @export
growing_days_next_year <- function(from, to, plant_date, harvest_date) {
    .Call(`_wsim_agriculture_growing_days_next_year`, from, to, plant_date, harvest_date)
}

#' Return the maximum number of growing days since planting that contribute to a harvest this year.
#' 
#' @inheritParams first_growing_day
#' 
#' @export
days_since_planting_this_year <- function(from, to, plant_date, harvest_date) {
    .Call(`_wsim_agriculture_days_since_planting_this_year`, from, to, plant_date, harvest_date)
}

#' Return the maximum number of growing days since planting that contribute to a harvest next year.
#' 
#' @inheritParams first_growing_day
#' 
#' @export
days_since_planting_next_year <- function(from, to, plant_date, harvest_date) {
    .Call(`_wsim_agriculture_days_since_planting_next_year`, from, to, plant_date, harvest_date)
}

#' Compute the maximum number of growing days between the most recent planting date
#' and a range of dates
#' 
#' @inheritParams first_growing_day
#' @export
days_since_planting_this_season <- function(from, to, plant_date, harvest_date) {
    .Call(`_wsim_agriculture_days_since_planting_this_season`, from, to, plant_date, harvest_date)
}

#' Determine if a planting occured between two dates that will result in a harvest this year
#' 
#' @inheritParams first_growing_day
#' @export
planted_for_this_year <- function(from, to, plant_date, harvest_date) {
    .Call(`_wsim_agriculture_planted_for_this_year`, from, to, plant_date, harvest_date)
}

#' Determine if a planting occured between two dates that will result in a harvest next year
#' 
#' @inheritParams first_growing_day
#' @export
planted_for_next_year <- function(from, to, plant_date, harvest_date) {
    .Call(`_wsim_agriculture_planted_for_next_year`, from, to, plant_date, harvest_date)
}

#' Calculate the length of the drowing season in days
#' 
#' @inheritParams first_growing_day
#' @export
growing_season_length <- function(plant_date, harvest_date) {
    .Call(`_wsim_agriculture_growing_season_length`, plant_date, harvest_date)
}

#' Disaggregate a matrix by duplicating each cell a fixed number of times
#' 
#' @param mat    matrix to disaggregate
#' @param factor number of times to copy each row and column 
#' @return matrix having dimensions of \code{dim(mat)*factor}
#' 
#' @export
disaggregate <- function(mat, factor) {
    .Call(`_wsim_agriculture_disaggregate`, mat, factor)
}

disaggregate_pfun <- function(m1, m2, op, na_rm) {
    .Call(`_wsim_agriculture_disaggregate_pfun`, m1, m2, op, na_rm)
}

#' Estimate loss due to stress (water surplus/water deficit/heat/cold)
#'
#' @param  rp       return period (positive) of stress
#' @param  rp_onset return period associated with the onset of loss
#' @param  rp_total return period associated with total loss
#' @param  power    exponent used in loss calculation; at higher values,
#'                  loss occurs at greater return periods.
#' @return loss fraction (0 to 1)
#' @export
loss_function <- function(rp, rp_onset, rp_total, power) {
    .Call(`_wsim_agriculture_loss_function`, rp, rp_onset, rp_total, power)
}

#' Compute the mean day-of-year
#' 
#' @param x a vector representing days of the year (1-365)
#' @return the mean date
#' @export
mean_doy <- function(x) {
    .Call(`_wsim_agriculture_mean_doy`, x)
}

#' Parse a condensed crop calendar in the format used by MIRCA2000
#' 
#' @param filename     full path to crop calendar file
#' @param header_lines number of header lines to skip [default: 4]
#' @return             data frame with columns for unit_code, crop, 
#'                     subcrop, planting month, and harvesting month
#' @export
parse_mirca_condensed_crop_calendar <- function(filename, header_lines = 4L) {
    .Call(`_wsim_agriculture_parse_mirca_condensed_crop_calendar`, filename, header_lines)
}

#' Reclassify the values in a numeric vector
#' 
#' @param x       a vector of values to reclassify
#' @param reclass a Nx2 matrix with original values in the first
#'                column and reclassified values in the second 
#'                column
#' @param na_default boolean indicating whether to reclassify values
#'                   that do not appear in \code{reclass} as \code{NA},
#'                   or raise an exception
#' @return reclassified vector having the same dimensions as \code{x}
#' @export
reclassify <- function(x, reclass, na_default) {
    .Call(`_wsim_agriculture_reclassify`, x, reclass, na_default)
}

