# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the sum of defined elements for each row and col in a 3D array
#'
#' @param v 3D array that may contain NA values
#'
#' @return a matrix with the sum for each [row, col, ]
#' @export
stack_sum <- function(v) {
    .Call(`_wsim_distributions_stack_sum`, v)
}

#' Compute the mean defined element for each row and col in a 3D array
#'
#' @param v 3D array that may contain NA values
#'
#' @return a matrix with the mean value for each [row, col, ]
#' @export
stack_mean <- function(v) {
    .Call(`_wsim_distributions_stack_mean`, v)
}

#' Compute the minimum defined element for each row and col in a 3D array
#'
#' @param v 3D array that may contain NA values
#'
#' @return a matrix with the minimum value for each [row, col, ]
#' @export
stack_min <- function(v) {
    .Call(`_wsim_distributions_stack_min`, v)
}

#' Compute the index of the minimum defined element for each row and col in a 3D array
#'
#' Returned value is indexed beginning at 1
#'
#' @param v 3D array that may contain NA values
#'
#' @return a matrix with the minimum index for each [row, col, ]
#' @export
stack_which_min <- function(v) {
    .Call(`_wsim_distributions_stack_which_min`, v)
}

#' Compute the maximum defined element for each row and col in a 3D array
#'
#' Returned value is indexed beginning at 1
#'
#' @param v 3D array that may contain NA values
#'
#' @return a matrix with the maximum value for each [row, col, ]
#' @export
stack_max <- function(v) {
    .Call(`_wsim_distributions_stack_max`, v)
}

#' Compute the index of the maximum defined element for each row and col in a 3D array
#'
#' @param v 3D array that may contain NA values
#'
#' @return a matrix with the maximum index for each [row, col, ]
#' @export
stack_which_max <- function(v) {
    .Call(`_wsim_distributions_stack_which_max`, v)
}

#' Compute the number of defined elements for each row and col in a 3D array
#'
#' @param v 3D array that may contain NA values
#'
#' @return a matrix with the computed count for each [row, col, ]
#' @export
stack_num_defined <- function(v) {
    .Call(`_wsim_distributions_stack_num_defined`, v)
}

#' Compute the fraction of defined elements for each row and col in a 3D array
#'
#' @param v 3D array that may contain NA values
#'
#' @return a matrix with the computed fraction for each [row, col, ]
#' @export
stack_frac_defined <- function(v) {
    .Call(`_wsim_distributions_stack_frac_defined`, v)
}

#' Compute the fraction of defined elements above zero for each row and col in a 3D array
#'
#' @param v 3D array that may contain NA values
#'
#' @return a matrix with the computed fraction for each [row, col, ]
#' @export
stack_frac_defined_above_zero <- function(v) {
    .Call(`_wsim_distributions_stack_frac_defined_above_zero`, v)
}

#' Compute a given quantile of defined elements for each row and col in a 3D array
#'
#' @param v 3D array that may contain NA values
#' @param q a quantile to compute, q within [0,1]
#'
#' @return a matrix with the specified quantile for each [row, col, ]
#' @export
stack_quantile <- function(v, q) {
    .Call(`_wsim_distributions_stack_quantile`, v, q)
}

#' Compute a given weighted quantile of defined elements for each row and col in a 3D array
#'
#' @param v a 3D array that may contain NA values
#' @param w a 2D vector of weights, having the same length as the third dimension of \code{v}
#' @param q a quantile to compute, q within [0, 1]
#'
#' @return a matrix with the specified quantile for each [row, col, ]
#' @export
stack_weighted_quantile <- function(v, w, q) {
    .Call(`_wsim_distributions_stack_weighted_quantile`, v, w, q)
}

#' Compute a weighted mean of defined elements for each row and col in a 3D array
#'
#' @param v a 3D array that may contain NA values
#' @param w a 2D vector of weights, having the same length as the third dimension of \code{v}
#'
#' @return a matrix with the specified quantile for each [row, col, ]
#' @export
stack_weighted_mean <- function(v, w) {
    .Call(`_wsim_distributions_stack_weighted_mean`, v, w)
}

#' Compute the median of defined elements for each row and col in a 3D array
#'
#' @param v 3D array that may contain NA values
#'
#' @return a matrix with the median for each [row, col, ]
#' @export
stack_median <- function(v) {
    .Call(`_wsim_distributions_stack_median`, v)
}

#' Sort each slice [i, j, ] in an array
#'
#' @param v 3D array that may contain NA values
#'
#' @return a matrix with the median for each [row, col, ]
#' @export
stack_sort <- function(v) {
    .Call(`_wsim_distributions_stack_sort`, v)
}

#' Extract a slab of n elements from an array, with a variable starting point
#'
#' @param v     a three-dimemsional array
#' @param start a matrix containing start indices along the third dimension of \code{v}
#' @param n     the number of elements to extract along the third dimension
#' @param fill  a fill value to use where \code{start[i, j] < 1 | start[i, j] + n > dim(v)[3]},
#'              or a function taking no arguments that will be called to obtain fill values
#' @export
stack_select <- function(v, start, n, fill) {
    .Call(`_wsim_distributions_stack_select`, v, start, n, fill)
}

#' Compute the rank of each element in a matrix, returning the minimum in case of ties
#'
#' @param x   a matrix of values to rank
#' @param obs a 3D array of observations against which each value in x should be ranked
#'
#' @return the rank of \code{x} after it is added to \code{obs}, for each (i, j) in \code{x}
#' @export
stack_min_rank <- function(x, obs) {
    .Call(`_wsim_distributions_stack_min_rank`, x, obs)
}

#' Compute the rank of each element in a matrix, returning the maximum in case of ties
#'
#' @param x   a matrix of values to rank
#' @param obs a 3D array of observations against which each value in x should be ranked
#'
#' @return the rank of \code{x} after it is added to \code{obs}, for each (i, j) in \code{x}
#' @export
stack_max_rank <- function(x, obs) {
    .Call(`_wsim_distributions_stack_max_rank`, x, obs)
}

#' Quantile function for the Pearson Type-III distribution
#'
#' The provided distribution parameters (\code{location}, \code{scale},
#' \code{shape}) must have either a length of \code{1}, or the same length
#' as \code{x}.
#'
#' @param x        vector of probabilities
#' @param location vector of location parameters
#' @param scale    vector of scale
#' @param shape    vector of shape parameters
#' @return quantiles associated with each probability \code{x}
#'
#' @export
quape3 <- function(x, location, scale, shape) {
    .Call(`_wsim_distributions_quape3`, x, location, scale, shape)
}

#' Quantile function for the generalized extreme value (GEV) distribution
#'
#' @inheritParams quape3
#' @export
quagev <- function(x, location, scale, shape) {
    .Call(`_wsim_distributions_quagev`, x, location, scale, shape)
}

#' Cumulative distribution function for the Pearson Type-III distribution
#'
#' The provided distribution parameters (\code{location}, \code{scale},
#' \code{shape}) must have either a length of \code{1}, or the same length
#' as \code{x}.
#'
#' @param x        vector of quantiles
#' @param location vector of location parameters
#' @param scale    vector of scale
#' @param shape    vector of shape parameters
#' @return probability assocated with each quantile \code{x}
#'
#' @export
cdfpe3 <- function(x, location, scale, shape) {
    .Call(`_wsim_distributions_cdfpe3`, x, location, scale, shape)
}

#' Cumulative distribution function for the generalized extreme value (GEV) distribution
#'
#' @inheritParams cdfpe3
#' @export
cdfgev <- function(x, location, scale, shape) {
    .Call(`_wsim_distributions_cdfgev`, x, location, scale, shape)
}

#' Bias-correct a forecast using GEV distribution
#'
#' Bias-correct a forecast using quantile-matching on computed distributions
#' of retrospective forecasts and observations.
#'
#' @param data           matrix representing forecast values
#' @param obs_location   location parameter from observed data
#' @param obs_scale      scale parameter from observed data
#' @param obs_shape      shape parameter from observed data
#' @param retro_location location parameter from retrospective data
#' @param retro_scale    scale parameter from retrospective data
#' @param retro_shape    shape parameter from retrospective data
#' @param extreme_cutoff clamping value for computed forecast quantiles
#'        (\code{1/extreme_cutoff < quantile < 1 - 1/extreme_cutoff})
#' @param when_dist_undefined assumed quantile of forecast when
#'        retrospective distribution is undefined
#'
#' @return a matrix with a corrected forecast
#'
#' @export
gev_forecast_correct <- function(data, obs_location, obs_scale, obs_shape, retro_location, retro_scale, retro_shape, extreme_cutoff, when_dist_undefined) {
    .Call(`_wsim_distributions_gev_forecast_correct`, data, obs_location, obs_scale, obs_shape, retro_location, retro_scale, retro_shape, extreme_cutoff, when_dist_undefined)
}

#' Bias-correct a forecast using Pearson Type-III distribution
#'
#' Bias-correct a forecast using quantile-matching on computed distributions
#' of retrospective forecasts and observations.
#'
#' @inheritParams gev_forecast_correct
#' @export
pe3_forecast_correct <- function(data, obs_location, obs_scale, obs_shape, retro_location, retro_scale, retro_shape, extreme_cutoff, when_dist_undefined) {
    .Call(`_wsim_distributions_pe3_forecast_correct`, data, obs_location, obs_scale, obs_shape, retro_location, retro_scale, retro_shape, extreme_cutoff, when_dist_undefined)
}

#' Compute a sample quantile of a given vector. NA values are ignored.
#'
#' This function is provided for improved performance over the built-in
#' \code{quantile} function. Interpolation is performed using the default
#' method 7 specified in documentation for \code{quantile}.
#'
#' @param v a vector of numeric values, possibly contining NAs
#' @param q quantile to compute
#'
#' @return sample quantile \code{q} of \code{v}
#'
#' @export
wsim_quantile <- function(v, q) {
    .Call(`_wsim_distributions_wsim_quantile`, v, q)
}

#' Substitute specifed values in a vector with replacements
#'
#' @param vals A vector in which some values should be replaced
#' @param subs A vector containing a sequence of replacement values,
#'             in the form val_1, replacement_1, val_2, replacement_2, ...
#'
#' @export
substitute <- function(vals, subs) {
    .Call(`_wsim_distributions_substitute`, vals, subs)
}

